name: Swift Test With Coverage

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Build
        run: swift build
      - name: Run tests
        run: bash ${GITHUB_WORKSPACE}/.github/workflows/test_and_report.sh
